messages:
    # The message when a user sends a duel request
    duelrequest: '%ply has sent you a duel request. Accept it by right clicking him.'
    
    # More messages
settings:
    # Set the timeout (in seconds)
    timeout: 60