messages:
    # The message to a user when a user sends a duel request
    duelrequest: '%ply has sent you a duel request. Accept it by right clicking him.'
    # The message when a user sends a duel request
    requestsent: 'The duel request has been sent.'
    # The message when a user sends a request twice
    alreadyrequested: 'You already sent %ply a request!'
    # The message when a request gets accepted
    requestaccepted: 'You accepted the duel request.'
    # The message when a user accepts a request
    acceptedrequest: '%ply accepted your request.'
    # The message when a user is in combat (if useincombat: false)
    cannotuseincombat: 'You cannot duel while fighting.'
    # The message when a user is already in a duel
    alreadyinduel: 'You are already in a duel!'
    # The message when a user lost the duel
    youlost: 'You lost the duel!'
    # The message when a user wins the duel
    youwon: 'You won the duel!'
    # More messages
kit:
    # Will be ignored if (ownstuff: true)
    # Armor
    armor:
        helmet: 298 1
        chestplate: 299 1
        leggings: 300 1
        boots: 301 1
    # Inventory
    inventory:
        - 272 1
        - 261 1
        - 262 32
winitems:
    # Will be ignored if (items: false)
    -
    -
    -
settings:
    # Set the request timeout (in minutes)
    timeout: 2
    # (false = kit | true = own stuff)
    ownstuff: false
    # Set duel use in combat
    useincombat: true
    # Combat Time (in seconds)
    combattime: 6
    # Should you win items?
    items: true
mysql:
    # Used for Stats
    url: jdbc:mysql://localhost:3306/database
    username: user
    password: pw